# Generated by Django 2.0 on 2018-01-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival', models.CharField(max_length=8, verbose_name='arrival time')),
                ('departure', models.CharField(max_length=8, verbose_name='departure time')),
            ],
        ),
    ]
